example outputting to Tenere controller
heronarts/LX pull request #4
Opened 2018-03-23 04:50 UTC by nargetdev

I decreased the size of the model (derived from the grid_model(30,30) instantiation)  because I see an index out of bounds exception when it's bigger.  Not sure what that's about.  Also I made the `fixtureToIndices` method of LXFixture public so I could extract the indices when needed from outside.  I think it would probably be a better idea to expose a method of LXFixture to get the indices.

2018-03-23 04:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/heronarts/LX?pullRequest=4) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/heronarts/LX?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/heronarts/LX?pullRequest=4) it.</sub>

2018-03-26 19:53 UTC, mcslee requested changes
Also made a change here so there's a public utility function for getting a list of point indices from any LXFixture, which is LXFixture.Utils.getIndices(LXFixture fixture)

https://github.com/heronarts/LX/commit/01e6a2654c2cd8fc10810a27d0919a0927d64e16

2018-03-26 19:53 UTC, mcslee commented on examples/LXHeadless/src/heronarts/lx/headless/LXHeadless.java
> +import heronarts.lx.output.*;
Are you using an IDE? Better to specifically enumerate only the dependencies that are used. Eclipse or IntelliJ should both do this...

2018-03-26 19:53 UTC, mcslee commented on examples/LXHeadless/src/heronarts/lx/headless/LXHeadless.java
> +    return new GridModel(10,17);
Before changing this, I'd love to see what the IndexOutOfBounds exception was that was being caused by 30, 30. That's concerning, implies that some size limit was being improperly hardcoded elsewhere...

2018-03-26 19:53 UTC, mcslee commented on examples/LXHeadless/src/heronarts/lx/headless/LXHeadless.java
> +      String[] controller_ips = { "10.200.1.146", "10.200.1.195", "10.200.1.197"};
Minor naming convention thing, but should keep the style conventions standard in here. lower_caps_underscore shouldn't be used here, rather should be camelCase.

I'm also not sure these specific IP addresses and Tenere-specific output classes ought to go in the base project, happy to let this slide but let's try to keep project-specific stuff to a minimum in here.

2018-06-07 02:17 UTC, mcslee commented
Yo - so it seems like the merge action here has gotten a little weird. Have you rebased your branch against heronarts:master? It looks like all the diffs that I created since are being double-included in the change-set here, rather than it being re-based against an update.

Do you want to do:
git pull --rebase

In your branch from the point that had your commits, and then generate a new clean pull request based upon that?

2018-06-07 23:26 UTC, nargetdev commented
Ok yea, I felt like there might be some weirdness – I’ll try again when I have a second.  There should only be like 15 lines of code added to the example, and then the TenereController.java class

From: Mark Slee
Sent: Wednesday, June 6, 2018 7:17 PM
To: heronarts/LX
Cc: Nathan Argetsinger; Author
Subject: Re: [heronarts/LX] example outputting to Tenere controller (#4)

Yo - so it seems like the merge action here has gotten a little weird. Have you rebased your branch against heronarts:master? It looks like all the diffs that I created since are being double-included in the change-set here, rather than it being re-based against an update.
Do you want to do:
git pull --rebase
In your branch from the point that had your commits, and then generate a new clean pull request based upon that?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2020-05-12 00:31 UTC, closed without merging